name: job1

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  DependenciesAnalysis:
    name: Analyse des dépendances
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Lancer OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v2.0.2
        with:
          scan-args: |
            --lockfile=app/gradle.lockfile
            --format=sarif
            --output=results.sarif
        continue-on-error: true

      - name: Envoyer le rapport au tableau de bord de sécurité
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
