name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  DependenciesAnalysis:
    name: Analyse des dépendances
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Lancer OSV Scanner
        uses: google/osv-scanner-action@v1
        with:
          directory: '.'

      - name: Envoyer le rapport au tableau de bord de sécurité
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
